### ISSUE TITLE
Tracking issue: Type hints

### ISSUE THREAD

**Issue by patrick-rivos** [IBM/microprobe#39]
Type hints are very helpful when reading/refactoring/debugging code. They can help show issues without running the code, and highlight edge cases before they're ever executed.

Notes:
**Q**: Why wrap imports in an `if TYPE_CHECKING:` statement?
**A**: Otherwise, we get circular dependencies. Since types aren't actually used at runtime, imports can be safely gated so they're only included when type checking.

**Q**: Why not annotate return types?
**A**: The derived return types include things like `None`, which people are often tempted to omit when typing a function. Allowing MyPy to derive the types on its own ensures we are being honest and get warned when a function's output does not match our expectations.

Directories to add type hints to:
- [ ]  `src/microprobe`
  - [ ] `code` #38
  - [ ] `driver`
  - [ ] `model`
  - [ ] `passes`
  - [ ] `schemas`
  - [ ] `target`
  - [ ] `utils`
  - [ ] other files in this dir
- [ ] `targets`
  - [ ] `generic`
  - [ ] `powerpc`
  - [ ] `riscv`

**Comment by rbertran** [comment]
Base on the discussion we had [here](https://github.com/IBM/microprobe/pull/42), I'd update this issue to add another a couple of items:
- [ ] Add an extra step Run the `mypy` as a CI step in Travis to perform static type check validation
- [ ] Enable `typeguard` during the execution of the CI tests to perform dynamic type check validation during tests (ensure we do not affect production code performance)
